name: Contribution Graph
on:
  schedule:
  - cron: "0 */1 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Main Workflow
    steps:
      - uses: actions/checkout@v2
      - uses:  Sabyasachi-Seal/3DContributionGraph@CustomFolderV3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name Sabyasachi Seal
          git config user.email yoboy907@gmail.com
          git pull
          git add -A .
          git commit -m "Update 3D Graph"
          git push
